### ISSUE TITLE
packages cannot be correctly compiled. and NAMESPACE is not correctly generated

### ISSUE THREAD

**Issue by ghost** [nlmixrdevelopment/rxModels#1]
I am actually not sure if this is the right place to ask the question. I suspect it is something related not only to RxODE. But it would be great if I can get any hints in where it went wrong.

I have followed the guides in the article on how to save the ODE models to use for other packages and failed. I have been using a work-around by just compiling the models on the fly. But I really would like to have a package that just contain all the relevant  models and then to use it without compiling it every time.

The example failed-to-compile package is under this repository below.  And you can see the NAMESPACE is not correctly modified by roxygen2. exported functions are not there. 

github.com/zhenglei-gao/odeModels

The error messages look like (on my own laptop another directory with a different name) 

```
In function `R_init0_effectmodels_RxODE_models':
   C:\Projects\EMod\GitLab\effectmodels\src/effectmodels_compiled.h:15: undefined reference to `R_init0_effectmodels_ITode'



collect2.exe: error: ld returned 1 exit status
   no DLL was created
   ERROR: compilation failed for package 'effectmodels'
```

**Comment by ghost** [comment]
Also if I run the check function, here is the log file:

```
* using log directory 'C:/Projects/EMod/GitLab/effectmodels.Rcheck'
* using R version 3.5.1 (2018-07-02)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'effectmodels/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'effectmodels' version '0.1.0'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... NOTE
Found the following apparent object files/libraries:
  inst/rx/effectmodels_SDode.dll
Object files/libraries should not be included in a source package.
* checking if there is a namespace ... OK
* checking for executable files ... WARNING
Found the following executable file:
  inst/rx/effectmodels_SDode.dll
Source packages should not contain undeclared executable files.
See section 'Package structure' in the 'Writing R Extensions' manual.
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'effectmodels' can be installed ... ERROR
Installation failed.
See 'C:/Projects/EMod/GitLab/effectmodels.Rcheck/00install.out' for details.
* DONE
Status: 1 ERROR, 1 WARNING, 1 NOTE
```

**Comment by ghost** [comment]
Actually it is indeed my system issue. I tried to do the same thing under Linux and it just worked. 

I have checked the Rtools path, the BINPREF, everything looks fine but somehow the package won't compile properly. Anyway, it is my specific issue related to company computer setups. I will close the issue here.

**Comment by mattfidler** [comment]
Thanks @zhenglei-gao 

Company computers can do that.  Thank you for looking into this.

Of course if you need help, please feel free to reach out.
